"""initial_schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_daily_budget',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.CheckConstraint('spent_usd >= 0 AND reserved_usd >= 0 AND limit_usd >= 0'),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('deletion_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_normalized', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_tokens_expires_at'), 'auth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('creation_key', sa.String(length=80), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('seller_notes', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ai_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_resolutions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'ready')"),
    sa.CheckConstraint('version >= 1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'creation_key')
    )
    op.create_index('ix_cards_owner_history', 'cards', ['user_id', 'deleted_at', 'updated_at', 'id'], unique=False)
    op.create_table('daily_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('accepted_jobs', sa.Integer(), nullable=False),
    sa.Column('created_drafts', sa.Integer(), nullable=False),
    sa.CheckConstraint('accepted_jobs >= 0 AND created_drafts >= 0'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('monthly_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('initial_limit', sa.Integer(), nullable=False),
    sa.Column('initial_used', sa.Integer(), nullable=False),
    sa.Column('initial_reserved', sa.Integer(), nullable=False),
    sa.Column('regeneration_limit', sa.Integer(), nullable=False),
    sa.Column('regeneration_used', sa.Integer(), nullable=False),
    sa.Column('regeneration_reserved', sa.Integer(), nullable=False),
    sa.CheckConstraint('initial_used + initial_reserved <= initial_limit'),
    sa.CheckConstraint('initial_used >= 0 AND initial_reserved >= 0 AND regeneration_used >= 0 AND regeneration_reserved >= 0'),
    sa.CheckConstraint('regeneration_used + regeneration_reserved <= regeneration_limit'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'period')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('card_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'position'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_card_images_card_id'), 'card_images', ['card_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('field_path', sa.String(length=80), nullable=True),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('provider_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('rules_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_period', sa.String(length=7), nullable=False),
    sa.Column('quota_bucket', sa.String(length=16), nullable=False),
    sa.Column('quota_state', sa.String(length=16), nullable=False),
    sa.CheckConstraint("operation IN ('initial','regenerate_all','regenerate_field')"),
    sa.CheckConstraint("quota_state IN ('reserved','consumed','released')"),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')"),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_generation_jobs_card_id'), 'generation_jobs', ['card_id'], unique=False)
    op.create_index('ix_jobs_lease', 'generation_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_jobs_one_active_per_user', 'generation_jobs', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('queued','running')"))
    op.create_index('ix_jobs_queue', 'generation_jobs', ['status', 'created_at'], unique=False)
    op.create_table('ai_call_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('thinking_tokens', sa.Integer(), nullable=True),
    sa.Column('budget_day', sa.String(length=10), nullable=False),
    sa.Column('reserved_cost', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('budget_state', sa.String(length=16), nullable=False),
    sa.Column('cost_basis', sa.String(length=16), nullable=False),
    sa.Column('price_version', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt_number')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_call_usage')
    op.drop_index('ix_jobs_queue', table_name='generation_jobs')
    op.drop_index('ix_jobs_one_active_per_user', table_name='generation_jobs', postgresql_where=sa.text("status IN ('queued','running')"))
    op.drop_index('ix_jobs_lease', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_card_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_card_images_card_id'), table_name='card_images')
    op.drop_table('card_images')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('monthly_usage')
    op.drop_table('daily_usage')
    op.drop_index('ix_cards_owner_history', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_expires_at'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('worker_heartbeats')
    op.drop_table('users')
    op.drop_table('deletion_events')
    op.drop_table('ai_daily_budget')
    # ### end Alembic commands ###
